spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: MyHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
application:
  jwt:
    secretKey: ed4667fac1ca35c325e7298c05cd71e8f7d0ae5b46b48c3956cdc9b587ca5d0e
    expiration: 43200000   # 12시간
    refreshExpiration: 604800000  # 7일